version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nops-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ph3mf5q4s8ba"
s3_prefix = "nops-test"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
